"""add track_record and geo_focus to user

Revision ID: e85ed8ecca7b
Revises: 73edd06da754
Create Date: 2025-11-12 14:48:05.485039

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e85ed8ecca7b'
down_revision = '73edd06da754'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('track_record', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('geo_focus', sa.String(length=150), nullable=True))
        batch_op.drop_column('investor_verified')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('investor_verified', sa.BOOLEAN(), nullable=False))
        batch_op.drop_column('geo_focus')
        batch_op.drop_column('track_record')

    # ### end Alembic commands ###
